name: Pinchflat
version: v2025.6.6
slug: pinchflat
description: Pinchflat Add-on
url: "https://github.com/Croydon/ha-addons"
webui: http://[HOST]:[PORT:8945]
arch:
  - aarch64
init: false
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
  - type: media
    read_only: false
    path: /downloads
  - type: addon_config
    read_only: false
    path: /config
options:
  TZ: "Europe/Berlin"
  BASIC_AUTH_USERNAME: ""
  BASIC_AUTH_PASSWORD: ""
schema:
  TZ: "str;description: Timezone;example: Europe/Berlin"
  BASIC_AUTH_USERNAME: "str;description: Basic auth username (leave blank to disable);example: user"
  BASIC_AUTH_PASSWORD: "str;description: Basic auth password (leave blank to disable);example: password"
video: true
ports:
  8945/tcp: 8945
ports_description:
  8945/tcp: Pinchflat web interface
image: ghcr.io/kieraneglin/pinchflat
