name: Pinchflat
version: v2025.6.6
slug: pinchflat
description: Pinchflat Add-on
url: "https://github.com/Croydon/ha-addon-pinchflat"
webui: http://[HOST]:[PORT:8945]
arch:
  - aarch64
init: false
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
  - type: media
    read_only: false
    path: /downloads
  - type: addon_config
    read_only: false
    path: /config
options:
  TZ: "Europe/Berlin"
schema:
  TZ: str
video: true
ports:
  8945/tcp: 8945
ports_description:
  8945/tcp: Pinchflat web interface
image: ghcr.io/kieraneglin/pinchflat
